UI improvements - forms
medic/cht-user-management pull request #172
Opened 2024-05-14 09:30 UTC by jonathanbataire

Fixes #131

2024-05-16 19:25 UTC, freddieptf requested changes

2024-05-16 19:25 UTC, freddieptf commented on src/liquid/place/create_form.html
> +    <a href="/" class="clear-btn" class="button">Cancel</a>
Do we have both a `btn` and `button` class? Also the `Save` button casts a shadow but the cancel one doesn't even though they should be visually on the save level

2024-05-16 19:25 UTC, freddieptf commented on src/scss/_input-forms.scss
> +                background-color: #337ab7;
This color is too strong for the hover state

2024-05-16 19:25 UTC, freddieptf commented on src/liquid/place/bulk_create_form.html
> +  <div  style="width: 70%; margin-bottom: 10px;" id="bulk-upload-file">
Lets not use inline styles like this

2024-05-16 19:25 UTC, freddieptf commented on src/liquid/place/bulk_create_form.html
> +    <a href="/" id="cancel" class="clear-btn">Cancel</a>
These two buttons should be on the same visual level but use the of class `btn` adds a shadow to the `Add` button

2024-05-16 19:25 UTC, freddieptf commented on src/liquid/place/bulk_create_form.html
> +  <div class="table-container">
We can do without the shadow on this table

2024-06-07 08:00 UTC, jonathanbataire commented
@freddieptf this is ready for review

2024-07-04 09:08 UTC, jonathanbataire commented
@freddieptf requesting review here this is ready

2025-01-15 11:58 UTC, jonathanbataire commented
stale

2025-01-15 11:58 UTC, closed without merging